// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Config from "./Config.bs.js";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as TestComponent from "./TestComponent.bs.js";

var defaultTheme = Config.Theme.make(undefined, undefined, undefined);

function start(theme) {
  return ReactDOMRe.renderToElementWithId(React.createElement(TestComponent.make, {
                  theme: theme
                }), "test");
}

export {
  defaultTheme ,
  start ,
  
}
/* defaultTheme Not a pure module */
