// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.bs.js";

function makeMain(primaryColorOpt, brandColorOpt, textColorOpt, baseFontSizeOpt, fontSizeSmallOpt, fontSizeLargeOpt, fontWeightOpt, param) {
  var primaryColor = primaryColorOpt !== undefined ? primaryColorOpt : "333333";
  var brandColor = brandColorOpt !== undefined ? brandColorOpt : "333333";
  var textColor = textColorOpt !== undefined ? textColorOpt : "000000";
  var baseFontSize = baseFontSizeOpt !== undefined ? baseFontSizeOpt : 10;
  var fontSizeSmall = fontSizeSmallOpt !== undefined ? fontSizeSmallOpt : 9;
  var fontSizeLarge = fontSizeLargeOpt !== undefined ? fontSizeLargeOpt : 13;
  var fontWeight = fontWeightOpt !== undefined ? fontWeightOpt : "bold";
  return {
          primaryColor: Css.hex(primaryColor),
          brandColor: Css.hex(brandColor),
          textColor: Css.hex(textColor),
          baseFontSize: Css.px(baseFontSize),
          fontSizeSmall: Css.pt(fontSizeSmall),
          fontSizeLarge: Css.pt(fontSizeLarge),
          fontWeight: fontWeight
        };
}

function makePrint(pageMarginOpt, footerHeightOpt, param) {
  var pageMargin = pageMarginOpt !== undefined ? pageMarginOpt : 10.0;
  var footerHeight = footerHeightOpt !== undefined ? footerHeightOpt : 20.0;
  return {
          pageMargin: Css.mm(pageMargin),
          footerHeight: Css.mm(footerHeight)
        };
}

var mainDefault = makeMain(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

var printDefault = makePrint(undefined, undefined, undefined);

function make(mainOpt, printOpt, param) {
  var main = mainOpt !== undefined ? mainOpt : mainDefault;
  var print = printOpt !== undefined ? printOpt : printDefault;
  return {
          main: main,
          print: print
        };
}

function main(theme) {
  return theme.main;
}

function print(theme) {
  return theme.print;
}

var Theme = {
  makeMain: makeMain,
  makePrint: makePrint,
  mainDefault: mainDefault,
  printDefault: printDefault,
  make: make,
  main: main,
  print: print
};

export {
  Theme ,
  
}
/* mainDefault Not a pure module */
