// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as Config from "./Config.bs.js";

var main = Config.Theme.makeMain(undefined, undefined, "202020", undefined, undefined, 30, "normal", undefined);

var theme = Config.Theme.make(main, undefined, undefined);

App.start(theme);

export {
  main ,
  theme ,
  
}
/* main Not a pure module */
