// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function getCard(theme) {
  return Curry._1(Css.style, {
              hd: Css.color(theme.main.textColor),
              tl: {
                hd: Css.fontSize(theme.main.fontSizeSmall),
                tl: {
                  hd: Css.fontWeight(theme.main.fontWeight),
                  tl: /* [] */0
                }
              }
            });
}

var Styles = {
  getCard: getCard
};

function TestComponent(Props) {
  var theme = Props.theme;
  return React.createElement("div", {
              className: getCard(theme)
            }, "Testing");
}

var make = TestComponent;

export {
  Styles ,
  make ,
  
}
/* Css Not a pure module */
